on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Test Build

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/boettiger-lab/nasa-tops:latest
      options: --user root --security-opt seccomp=unconfined
    permissions:
      contents: write
    steps:
      - name: Quarto-inside-docker permissions
        run: git config --system --add safe.directory '*'
    
      - name: Check out repository
        uses: actions/checkout@v3

#      - name: Set up Quarto
#        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        run: |
             rm -rf _freeze
             quarto render
