on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/boettiger-lab/nasa-tops:latest
      options: --user root --security-opt seccomp=unconfined
    permissions:
      contents: write
    steps:
      - name: Quarto-inside-docker permissions
        run: git config --system --add safe.directory '*'
    
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Render and Publish
        if: github.repository == 'NASA-Openscapes/earthdata-cloud-cookbook'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
